rdcms:
  bugherd:
    user: "current_user"
    role: "admin"
    api: ""
  html2pdf_uid: "c5c13af822"
  use_solr: "false"
  url: "www.requestdev.com.br"
  use_ssl: "false"
  facebook:
    appid: "123456"
    opengraph_default_image: "/assets/open-graph.png"
  twitter:
    via: ""
    rel: requestdev
    hash: "requestdev sistemas, requestdev, request, development, dev, sistemas, system"
  geocode_ip_address: "true"

  dashboard:
    limit_itens: "10"
  upload:
    auto_save: "false"
  home:
    products:
      limit: "8"
    articles:
      limit: "6"
    galleries:
      limit: "4"
    facebook:
      box_size: "4"
  videos:
    # [Video, Standardfeed, User, Playlist]
    object: 'Playlist'
    # ID
    scope: 'PLN78J7sDciewBdMTaYosKKns30hyFUnJG'
    limit: '10'
    "api-version": '2'
  mailer:
    newsletter:
      from_name: "Requestdev Sistemas"
      from_email: notreplay@requestdev.com.br
  site:
    name: Requestdev Sistemas