rdcms:
  bugherd:
    user: "current_user"
    role: "admin"
    api: ""
  html2pdf_uid: "c5c13af822"
  use_solr: "false"
  url: "www.requestdev.com.br"
  use_ssl: "false"

  # Botões dos perfis nas redes sociais
  social_pages:
    facebook: https://www.facebook.com/Requestedev.com.br
    google-plus: https://plus.google.com/116782495692009309425
    twitter: https://twitter.com/requestd

  # Redes Sociais
  facebook:
    appid: "123456"
    opengraph_default_image: "/assets/open-graph.png"
  twitter:
    via: ""
    rel: requestdev
    hash: "requestdev sistemas, requestdev, request, development, dev, sistemas, system"
  geocode_ip_address: "true"

  dashboard:
    limit_itens: "10"
  upload:
    auto_save: "false"
  home:
    products:
      limit: "8"
    articles:
      limit: "6"
    galleries:
      limit: "4"

  videos:
    # [Video, Standardfeed, User, Playlist]
    object: 'Playlist'
    # ID
    scope: 'PLN78J7sDciewBdMTaYosKKns30hyFUnJG'
    limit: '10'
    "api-version": '2'
  mailer:
    newsletter:
      from_name: "Requestdev Sistemas"
      from_email: notreplay@requestdev.com.br
  # Informações da compania
  company:
    name: Requestdev Desenvolvimento e Consultoria LTDA
    address: Rua dos Caripunas, 75
    district: Bairro Urupá
    cep: 76.900-184
    city: Ji-Paraná
    state: Rondônia
    country: Brasil
    phone: "+55 (69) 3421-4346"
    email: "contato@requestdev.com.br"

  site:
    name: Requestdev Sistemas

  view:
    # Visualização
    application:
      header:
        logo: logo.png
        background: ""
        inner_background: ""
        padding: "10px 0 0"
      footer:
        background: ""
        padding: "15px 0 0"
        container_background: ""
    full_screen:
      logo: logo_fullscreen.png
      background: ""
      inner-background: ""
