rdcms:
  bugherd:
    user: "current_user"
    role: "admin"
    api: ""
  comments:
    commentator: "User"
  menus:
    recreate_cache: "false"
  widgets:
    recreate_cache: "false"
  html2pdf_uid: "c5c13af822"
  use_solr: "false"
  url: "www.requestdev.com.br"
  use_ssl: "false"

  article:
    preview:
      roles: "Admin"
    edit_link:
      user: "current_user"
      role: "admin"
    image_positions: "standard"
    cache_articles: "true"
    max_cache_24h: "false"
    article_index:
      link_to_article: "weiterlesen"
  remove_old_versions:
    active: "true"
    weeks: "2"
  visitors:
    send_confirmation_email: 'false'
  upload:
    convert_options: '-auto-orient -strip -flatten -normalize -quality 70 -interlace Plane'
  post:
    preview:
      roles: "Admin"
    edit_link:
      user: "current_user"
      role: "admin"
    cache_posts: "true"
    max_cache_24h: "false"

  # Botões dos perfis nas redes sociais
  social_pages:
    facebook: https://www.facebook.com/Requestedev.com.br
    google-plus: https://plus.google.com/116782495692009309425
    twitter: https://twitter.com/requestd

  # Redes Sociais
  facebook:
    appid: "123456"
    opengraph_default_image: "/assets/open-graph.png"
  twitter:
    via: ""
    rel: requestdev
    hash: "requestdev sistemas, requestdev, request, development, dev, sistemas, system"
  geocode_ip_address: "true"

  dashboard:
    limit_itens: "10"
  upload:
    auto_save: "false"
  home:
    products:
      limit: "8"
    articles:
      limit: "6"
    galleries:
      limit: "4"

  videos:
    # [Video, Standardfeed, User, Playlist]
    object: 'Playlist'
    # ID
    scope: 'PLN78J7sDciewBdMTaYosKKns30hyFUnJG'
    limit: '10'
    "api-version": '2'
  mailer:
    newsletter:
      from_name: "Requestdev Sistemas"
      from_email: notreplay@requestdev.com.br
  # Informações da compania
  company:
    name: Requestdev Desenvolvimento e Consultoria LTDA
    address: Rua Dom Augusto, 1196
    district: Bairro Centro
    cep: 76.900-103
    city: Ji-Paraná
    state: Rondônia
    country: Brasil
    phone: "+55 (69) 3421-4346"
    email: "contato@requestdev.com.br"
    year: "2011 - 2013"
    localization: -10.879028,-61.95147

  site:
    name: Requestdev Sistemas

  view:
    # Visualização
    application:
      header:
        logo: logo.png
        background: ""
        inner_background: ""
        padding: "10px 0 0"
      footer:
        background: ""
        padding: "15px 0 0"
        container_background: ""
      contact:
        background: ""
    full_screen:
      logo: logo_fullscreen.png
      background: ""
      inner-background: ""
  omniauth:
    google: # also used by the YouTube provider
      key: "632827312868.apps.googleusercontent.com"
      secret: "lJFcmxPbTDla8aYE1QiXz5YJ"
      token: ""
      refresh_token: ""
      expires_at: ""
