rdcms:
  bugherd:
    user: "current_user"
    role: "admin"
    api: ""
  comments:
    commentator: "User"
  menus:
    recreate_cache: "false"
  widgets:
    recreate_cache: "false"
  html2pdf_uid: "c5c13af822"
  use_solr: "false"
  page:
    default_title_tag: "Rdcms"
  article:
    image_positions: "standard"
    cache_articles: "true"
    max_cache_24h: "false"
    article_index:
      link_to_article: "weiterlesen"
  url: "www.requestdev.com.br"
  use_ssl: "false"
  facebook:
    appid: "123456"
    opengraph_default_image: "/assets/open-graph.png"
  geocode_ip_address: "false"

  dashboard:
    limit_itens: "10"
  home:
    products:
      limit: "8"
      box_size: "12"
    articles:
      limit: "5"
      box_size: "6"
    galleries:
      limit: "4"
      box_size: "6"
    facebook:
      box_size: "4"
